In [5]:
import numpy as np
a=np.array([4,6,5])
b=np.array([3,7,8])
print(a)
print(b)
print(a+b)
print(a*b)

[4 6 5]
[3 7 8]
[ 7 13 13]
[12 42 40]


In [6]:
a=np.array([4,8,"9"])
print(a)

['4' '8' '9']


In [7]:
import numpy as np
arr=np.array([16,38,26])
print(arr[1:])
print(arr[2:])


[38 26]
[26]


In [20]:
import numpy as np
arr=np.array([[10,28,39,45],[20,34,54,35]])
print(arr[0:2,0:4])
print(arr[0,2:3])
print(arr[1,3:])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(type(arr))
print(arr.dtype)
print(arr.astype(int))
print(arr.astype(str))


[[10 28 39 45]
 [20 34 54 35]]
[39]
[35]
(2, 4)
8
2
<class 'numpy.ndarray'>
int32
[[10 28 39 45]
 [20 34 54 35]]
[['10' '28' '39' '45']
 ['20' '34' '54' '35']]


In [33]:
import numpy as np
a=np.array([12,13,14])
b=np.array([15,16,17])
c=np.array([2])
print(np.add(a,b))
print(np.subtract(b,a))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.exp(a))
print(np.power(a,b))
print(a+b)

[27 29 31]
[3 3 3]
[180 208 238]
[0.8        0.8125     0.82352941]
[ 162754.791419    442413.39200892 1202604.28416478]
[-1073741824  1778525249  -586285056]
[27 29 31]


In [15]:
import numpy as np
a=np.array([[12,13],[13,14]])
b=np.array([[16,17],[12,18]])
print(np.concatenate([a,b]))
print(np.concatenate([[[12,13],[14,13]],[[2,5],[4,7]]],axis=1))
print(np.hstack([a,b]))
print(np.vstack([a,b]))

[[12 13]
 [13 14]
 [16 17]
 [12 18]]
[[12 13  2  5]
 [14 13  4  7]]
[[12 13 16 17]
 [13 14 12 18]]
[[12 13]
 [13 14]
 [16 17]
 [12 18]]


In [21]:
import numpy as np
a=np.array([12,23,14,23,25,12])
print(np.array_split(a,3))
b=np.array_split(a,3)
print(b[1])

[array([12, 23]), array([14, 23]), array([25, 12])]
[14 23]


In [1]:
import numpy as np
a=np.array([12,13,14,15])
b=np.array([[12,13],[13,14]])
print(np.append(a,10))
print(np.insert(a,2,23))
print(np.insert(b,[1,2],15,axis=1))
print(np.delete(a,[1]))

[12 13 14 15 10]
[12 13 23 14 15]
[[12 15 13 15]
 [13 15 14 15]]
[12 14 15]


In [1]:
import numpy as np
a=np.array([2,7,4,3,8,5])
b=np.array([[2,7,4,3,8,5],[3,1,6,4,7,2]])
print(np.sort(b,axis=1))
print(np.sort(b,axis=0))
print(np.sort(a))
c=np.sort(a)
print(np.where(a==4))
print(np.where(a%2==0))
print(np.searchsorted(c,8))
d=[True,False,False,True,True,False]
print(a[d])
e= a%2==1
print(a[e])


[[2 3 4 5 7 8]
 [1 2 3 4 6 7]]
[[2 1 4 3 7 2]
 [3 7 6 4 8 5]]
[2 3 4 5 7 8]
(array([2], dtype=int64),)
(array([0, 2, 4], dtype=int64),)
5
[2 3 8]
[7 3 5]


In [1]:
import numpy as np
a=np.array([20,87,56,35])
print(np.min(a))
print(np.max(a))
print(np.sum(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))


20
87
198
4
49.5
[ 20 107 163 198]
[     20    1740   97440 3410400]


In [8]:
import numpy as np 
import statistics as stats
a=np.array([12,23,13,34,24,13])
print(np.mean(a))
print(np.median(a))
print(stats.mode(a))
print(np.std(a))
print(np.var(a))
b=np.array([23,24,14,15,28,15])
print(np.corrcoef(a,b))



19.833333333333332
18.0
13
7.98783797754784
63.805555555555564
[[1.         0.10371884]
 [0.10371884 1.        ]]
